"""Per-task reproduction-script scaffolding (Phase 1 of the per-task split).

The split lets the harness run each reproduction task as its OWN process with its own
timeout, so a hang / segfault / OOM in one task (e.g. an expensive heatmap) only loses
that task instead of sinking every other task's artifacts -- the hard isolation that an
in-process ``try/except`` cannot provide.

This module is deterministic, harness-owned plumbing (no LLM):
- ``build_tasks_manifest`` derives ``tasks_manifest.json`` from ``repro_tasks.json``.
- ``render_run_experiment_dispatcher`` emits the ``run_experiment.py`` human entry point.
  Generated code may not use subprocess/importlib, so the dispatcher is generated by the
  HARNESS with STATIC imports of each task module and runs them in-process, each in its
  own ``try/except`` (soft isolation, for ``python run_experiment.py``). The runner runs
  ``tasks/<module>.py`` as subprocesses for the stronger process-level isolation.
- ``write_task_scaffolding`` drops ``tasks/__init__.py``, ``tasks_manifest.json`` and the
  dispatcher into a project.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from .io_runtime import io_slug


DEFAULT_SMOKE_TIMEOUT_S = 60
DEFAULT_FULL_TIMEOUT_S = 2000


def task_module_name(task_id: object, used: set[str] | None = None) -> str:
    """A valid, unique Python module name for a task id (for ``tasks/<module>.py``)."""
    slug = re.sub(r"[^0-9A-Za-z_]+", "_", str(task_id or "")).strip("_").lower()
    if not slug:
        slug = "task"
    if slug[0].isdigit():
        slug = "t_" + slug
    if used is not None:
        base, index, candidate = slug, 2, slug
        while candidate in used:
            candidate = f"{base}_{index}"
            index += 1
        slug = candidate
        used.add(slug)
    return slug


def build_tasks_manifest(
    tasks_doc: Any,
    *,
    smoke_timeout_s: int = DEFAULT_SMOKE_TIMEOUT_S,
    full_timeout_s: int = DEFAULT_FULL_TIMEOUT_S,
) -> dict[str, Any]:
    """Derive the per-task run manifest from a repro_tasks document.

    ``output_subdir`` uses :func:`io_slug` so it matches exactly the ``outputs/<slug>/``
    folder ``_io`` writes the task's artifacts into."""
    raw = tasks_doc.get("repro_tasks") if isinstance(tasks_doc, dict) else None
    entries: list[dict[str, Any]] = []
    used: set[str] = set()
    for index, task in enumerate(raw if isinstance(raw, list) else [], start=1):
        if not isinstance(task, dict):
            continue
        task_id = str(task.get("task_id") or "").strip() or f"task_{index:02d}"
        module = task_module_name(task_id, used)
        entries.append(
            {
                "task_id": task_id,
                "module": module,
                "script": f"tasks/{module}.py",
                "output_subdir": io_slug(task_id),
                "timeout_smoke_s": smoke_timeout_s,
                "timeout_full_s": full_timeout_s,
            }
        )
    return {"version": 1, "tasks": entries}


_DISPATCHER_HEADER = '''"""Auto-generated run-all dispatcher (geng-agent, do not edit).

Human entry point: `python run_experiment.py config_smoke.json`. Runs every reproduction
task in-process, each isolated in its own try/except so one failure does not sink the
others, then writes an aggregate outputs/summary.json. The harness runs each
tasks/<module>.py as its own subprocess for stronger process-level isolation."""
from __future__ import annotations

import json
import sys
from pathlib import Path

from src import _io

'''

_DISPATCHER_MAIN = '''

def main() -> int:
    config_path = sys.argv[1] if len(sys.argv) > 1 else "config_smoke.json"
    results = {}
    all_passed = True
    for task_id, run_task in _TASKS:
        try:
            run_task(config_path)
            results[task_id] = {"status": "ok"}
        except Exception as exc:
            results[task_id] = {"status": "error", "error": f"{type(exc).__name__}: {exc}"}
            all_passed = False
    output_dir = Path("outputs")
    output_dir.mkdir(parents=True, exist_ok=True)
    summary = {"config": config_path, "tasks": results, "all_passed": all_passed}
    (output_dir / "summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8"
    )
    return 0 if all_passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''


def render_run_experiment_dispatcher(manifest: dict[str, Any]) -> str:
    """Render run_experiment.py: STATIC imports of each task module + an in-process loop.

    Static imports (not importlib) keep the generated project scan-clean while still
    letting the human entry point run every task."""
    tasks = [t for t in manifest.get("tasks", []) if isinstance(t, dict) and t.get("module")]
    imports = "\n".join(f"from tasks import {t['module']} as _task_{t['module']}" for t in tasks)
    entries = "\n".join(f"    ({t['task_id']!r}, _task_{t['module']}.main)," for t in tasks)
    block = _DISPATCHER_HEADER
    if imports:
        block += imports + "\n"
    block += "\n_TASKS = [\n" + (entries + "\n" if entries else "") + "]\n"
    block += _DISPATCHER_MAIN
    return block


def write_task_scaffolding(project_dir: Path, manifest: dict[str, Any]) -> dict[str, Any]:
    """Write tasks/__init__.py, tasks_manifest.json and the run_experiment.py dispatcher.

    The dispatcher REPLACES any model-generated run_experiment.py (it is harness-owned)."""
    project_dir = Path(project_dir)
    tasks_dir = project_dir / "tasks"
    tasks_dir.mkdir(parents=True, exist_ok=True)
    init_path = tasks_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text("", encoding="utf-8", newline="\n")
    (project_dir / "tasks_manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    (project_dir / "run_experiment.py").write_text(
        render_run_experiment_dispatcher(manifest), encoding="utf-8", newline="\n"
    )
    return manifest


def load_tasks_manifest(project_dir: Path) -> dict[str, Any] | None:
    """Read tasks_manifest.json from a project, or None if absent/invalid (the runner
    falls back to the legacy single-script path when this returns None)."""
    path = Path(project_dir) / "tasks_manifest.json"
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    if isinstance(data, dict) and isinstance(data.get("tasks"), list) and data["tasks"]:
        return data
    return None
